import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavbarNextUi from "../componentsUi/NavbarNextUi";
import "./globals.css";
import { Providers } from "./providers";
import "/css/fontStyle.css";
import "/css/Uiverse.css";

const fontStyle = Inter({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Lesson English",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning={true}>
      <body className={fontStyle.className}>
        <Providers>
          <div className="overflow-x-hidden">
            <NavbarNextUi />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
